---
 - name: AWS components installation
   hosts: localhost
   connection: local
   gather_facts: false  
   tags: provisioning

   vars:
    instance_type: t2.micro
    security_group: demoSG
    image: ami-0c02fb55956c7d316
    region: us-east-1
    keypair: ansible
    count: 1

   tasks:
    - name: Create a security group on the default VPC
      local_action:
        module: ec2_group
        name: "{{ security_group }}"
        description: demo security group test
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 80
              - 443
              - 22
            cidr_ip:  0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
           
    - name: launching ec2 instance using Ansible
      local_action:
        module: ec2_instance
        security_group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        wait: yes
        key_name: "{{ keypair }}"
        state: present
        tags:
          Name: ansibleserver
        #vpc_subnet_id: default
        #assign_public_ip: yes
      register: ec2_instance

    - name:
      ansible.builtin.debug:
       msg: "{{ ec2_instance }}"

    - name: Wait for SSH connection for the ec2_instance to spin up
      wait_for:
        host: "{{ item.public_ip_address }}"
        port: 22
        delay: 10
      with_items: "{{ ec2_instance.instances }}"

    - name: Add the new EC2 instance to the test hosts groups
      add_host:
        name: "{{ item.public_ip_address }}"
        groups: test_host
      with_items: "{{ ec2_instance.instances }}"

 